### ISSUE TITLE
Missing imports

### ISSUE THREAD

**Issue by pavel-koval-gismart** [beamai/BeamAILite-iOS#1]
After installing package dependencies there is an error on attempt to import BeamAISDK: `Missing required modules: 'ARCoreAugmentedFaces', 'Amplitude_iOS'`
(Xcode 14, M1)

**Comment by peymanbateni** [comment]
Thanks for opening the issue @pavel-koval-gismart. I will try and recreate the error on my end and push a fix as soon as possible. Can you provide any additional details?

Thanks,
Peyman

**Comment by peymanbateni** [comment]
Hi @pavel-koval-gismart! We just pushed a fix at https://github.com/beamai/BeamAISDK-iOS. There was a minor issue involving compiled headers and public interfaces but it should be good now. To get the updated files, you will need to reimport the swift package from https://github.com/beamai/BeamAISDK-iOS. But since the version hasn't moved, Swift Package Manager may give you some revision mismatch issues. To reset your SPM cache and fix those errors, use this: https://stackoverflow.com/questions/72788019/where-is-swift-package-manager-cache-located-swift-5-7/72838880#72838880. 

Let me know if any other issues come up. Thank you again for pointing this out. I will leave the issue open for a few days just in case but if things are working, it would be amazing if you could let me know so I can close the issue.

**Comment by pavel-koval-gismart** [comment]
Hello!
With recent fix I've finally managed to integrate BeamAI SDK and now it working like charm.
Thank you for quick response!

**Comment by peymanbateni** [comment]
Hi @pavel-koval-gismart, glad to hear that. I'll go ahead and close this issue. Thank you very much for using our SDK!
